"""Generate deterministic P5 inputs. No cluster-side Python or submission wrapper."""
import argparse,json
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('runs',type=Path);a=p.parse_args();r=a.runs;o=r/'pices_p5';(o/'cases').mkdir(parents=True,exist_ok=True)
base={}
for line in (r/'cmbhf_EBA_PICES_P4.cfg').read_text().splitlines():
 line=line.split('#',1)[0].strip()
 if line:k,v=line.split('=',1);base[k]=v
# Final times are equal within each scenario, including timestep refinements.
variants=[('base',9,32,1,1),('dt_half',9,32,2,1),('dt_quarter',9,32,4,1),('grid_coarse',5,32,1,1),('grid_fine',13,32,1,1),('np_low',9,16,1,1),('np_high',9,64,1,1),('length_half',9,32,1,.5),('length_double',9,32,1,2)]
rows=[]
for scenario in ['cold','hot','assim']:
 for method in ['pg','pices']:
  for variant,n,np,refine,length in variants:
   if method=='pg' and (variant.startswith('np_') or variant.startswith('length_')):continue
   name=f'{scenario}_{method}_{variant}';dt=(1e-7 if scenario=='assim' else 1e-6)/refine;steps=4*refine
   rows.append(dict(name=name,scenario=scenario,method=method,variant=variant,nodes=n,particles=np if method=='pices' else 0,steps=steps,dt=dt,prescribed=scenario!='assim',length_scale=length))
# Coupled flow is compared separately from prescribed transport.
for scenario in ['cold','hot']:
 for method in ['pg','pices']:
  rows.append(dict(name=f'{scenario}_{method}_coupled',scenario=scenario,method=method,variant='coupled',nodes=9,particles=32 if method=='pices' else 0,steps=4,dt=1e-8,prescribed=False,length_scale=1))
for row in rows:
 cfg=base.copy();n=row['nodes'];assim=row['scenario']=='assim';pic=row['method']=='pices'
 cfg.update(dict(Solver='cgrad',levels='1',print_convergence='1',energy_solver=row['method'],tracer=str(int(pic)),pices_checkpoint='off',checkpointFrequency='1000000',nodex=str(n),nodey=str(n),nodez=str(n),mgunitx=str(n-1),mgunity=str(n-1),mgunitz=str(n-1),
 maxstep=str(row['steps']),maxtotstep=str(row['steps']+1),storage_spacing=str(row['steps']),CBF_frequency=str(row['steps']),CBF_use_advection='off' if pic else 'on',
 datafile='PICES_P5',refstate_file='refstate.txt',fixed_timestep=format(row['dt'],'.17g'),tracers_per_element=str(row['particles'] or 32),output_optional='tracer' if pic else '',
 p5_case=row['scenario'],p5_prescribed_velocity='on' if row['prescribed'] else 'off',p5_omega='4000',p5_length_scale=str(row['length_scale']),
 lith_age=str(int(assim)),lith_age_asml=str(int(assim)),lith_age_time=str(int(assim)),Q0='.3' if assim else '0',dissipation_number='.1' if assim else '0',
 phase_delta_rho='0,0,0',phase_delta_s='0,0,0',kT_exponent='.3' if assim else '0',kd_lower_prefactor='4.8' if assim else '4',
 lith_age_file='forcing/age.',flag_depth_file='forcing/trench.',flag_depth_new_file='forcing/trench.',tf_file='forcing/trench.',num_perturbations='1',perturbl='2',perturbm='2',perturblayer=str((n+1)//2),perturbmag='0'))
 if not row['prescribed']:cfg['vlowstep']='1000'
 (o/'cases'/f"{row['name']}.cfg").write_text('# P5 reconstructed feasibility experiment; generated by prepare_p5.py.\n'+'\n'.join(f'{k}={v}' for k,v in cfg.items())+'\n')
 for which in ['transport','assim']:
  f=o/f'refstate_{which}_{n}.txt'
  f.write_text('\n'.join(f'{1+.1*(n-1-i)/(n-1) if which=="assim" else 1:.17g} 1 {.8-.4*i/(n-1):.17g} 1 {1+.2*(n-1-i)/(n-1) if which=="assim" else 1:.17g}' for i in range(n))+'\n')
for n in [5,9,13]:
 f=o/f'forcing_{n}';f.mkdir(exist_ok=True)
 for age in range(4):
  (f/f'trench.{age}.xyz').write_text('')
  for cap in range(12):(f/f'age.{age}.{cap}').write_text((str(30+10*age)+'\n')*(n*n))
(o/'matrix.json').write_text(json.dumps(dict(schema=1,cases=rows,production_switch=False),indent=2)+'\n')
(o/'matrix.tsv').write_text('\n'.join(f"{x['name']}\t{x['nodes']}\t{x['steps']}\t{'assim' if x['scenario']=='assim' else 'transport'}" for x in rows)+'\n')
print(len(rows),'cases generated in',o)
