"""Generate a fully coupled same-partition restart gate (synthetic forcing)."""
import argparse,json,shutil
from pathlib import Path
from prepare_p8a import edit

def prepare(runs):
    out=runs/'pices_p8c';out.mkdir(exist_ok=True)
    text=edit((runs/'pices_p8b/multigrid.cfg').read_text(),dict(p5_case='off',pices_checkpoint='on',checkpointFrequency=2,maxstep=4,maxtotstep=5,datafile='PICES_P8c'))
    text=text.replace('# P5 reconstructed feasibility experiment; generated by prepare_p5.py.', '# P8c coupled restart gate; synthetic forcing, standard initialization.')
    rows=[]
    for name,opts,first,last in [('continuous',{},1,4),('split',dict(maxstep=2,maxtotstep=3),1,2),('restart',dict(restart='on',solution_cycles_init=2,datadir_old='../split/DATA/%RANK',datafile_old='PICES_P8c'),3,4)]:
        (out/(name+'.cfg')).write_text(edit(text,opts));rows.append(dict(name=name,first=first,last=last))
    shutil.copy(runs/'pices_p8b/refstate.txt',out)
    shutil.copytree(runs/'pices_p8b/forcing',out/'forcing',dirs_exist_ok=True,ignore=shutil.ignore_patterns('._*'))
    (out/'matrix.json').write_text(json.dumps(dict(stage='P8c',cases=rows),indent=2)+'\n')
    (out/'matrix.tsv').write_text(''.join(f"{r['name']}\t{r['first']}\t{r['last']}\n" for r in rows))
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('runs',type=Path);prepare(p.parse_args().runs)
