#!/bin/sh

abort() {
	#echo "$1" > /dev/null 1>&2
	exit 1
}

toconvert="$1"
age="$2"

test -z "$toconvert" && abort "please specify a directory to convert"

awkscript="$0".awk

{
cd "$toconvert"

test -e "$awkscript" || abort "can't find awk script needed for conversion"

for file in global.*.$age.txt ; do
#for file in out_etopoR0.5.txt ; do
	awk -f "$awkscript" < $file > ${file%.txt}.vtk
done
}
